---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
    
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |